name: CI Pipeline - Docker Build & Push

# 1. When should this run? Every time you push code.
on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 2. Download your code
    - name: Checkout Code
      uses: actions/checkout@v4

    # 3. Build the container
    - name: Build Docker Image
      run: docker build -t my-cloud-app .

    # 4. Use your secret keys to log in to Docker Hub
    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    # 5. Put your specific "shipping label" on the container
    - name: Tag the Image for Docker Hub
      run: docker tag my-cloud-app ${{ secrets.DOCKER_USERNAME }}/my-cloud-app:latest

    # 6. Upload it to the global library!
    - name: Push Image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/my-cloud-app:latest